version: "3.8"

services:
  dupish:
    container_name: dupish-bento
    build:
      context: .
      dockerfile: dockers/Dockerfile.bento
      args:
        version: '0.0.1'
    ports:
      - "3000:3000"
    # volumes:
    #   - dupish-bento:/data
    # environment:
    #   DUPISH_VOLUMES: /data
    networks:
      - dupish-network
    command: "poetry run bentoml serve service:svc --working-dir inference"
    #command: "poetry run bentoml serve service:ISC_FT_V107 --working-dir inference" 
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://127.0.0.1:3000/healthz || exit 1
      interval: 30s
      timeout: 20s
      retries: 3

  backend:
    container_name: dupish-backend
    build:
      context: .
      dockerfile: dockers/Dockerfile.backend
      args:
        version: '0.0.1'
    ports:
        - "81:81"
    command: "poetry run uvicorn backend.main:app --port 81 --host 0.0.0.0"
    depends_on:
      - dupish
    networks:
      - dupish-network

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data
    depends_on:
      - dupish
    networks:
      - dupish-network
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_VOLUMES: /data
    command: "minio server --console-address :9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 20s
      retries: 3
    

  weaviate:
    container_name: weaviate
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.24.6
    ports:
    - 4281:8080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      # ENABLE_MODULES: 'text2vec-cohere,text2vec-huggingface,text2vec-palm,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai'
      CLUSTER_HOSTNAME: 'node1'
      # To maximize import speed, enable asynchronous indexing and use gRPC batch imports. (https://weaviate.io/developers/weaviate/manage-data/import)
      ASYNC_INDEXING: 'true'

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    depends_on:
      - dupish
    networks:
      - dupish-network
    command: "redis-server --appendonly yes --requirepass _r3d1s_"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 20s
      retries: 3


networks:
  dupish-network:
    driver: bridge



volumes:
  dupish-bento:
    driver: local
  minio:
    driver: local
  weaviate_data:
    driver: local
  redis_data:
    driver: local

