version: "3.8"

services:
  dupish:
    container_name: dupish-bento
    build:
      context: .
      dockerfile: dockers/Dockerfile.bento
      args:
        version: '0.0.1'
    ports:
      - "3000:3000"
    # volumes:
    #   - dupish-bento:/data
    # environment:
    #   DUPISH_VOLUMES: /data
    networks:
      - dupish-network
    command: "poetry run bentoml serve service:svc --working-dir inference"
    #command: "poetry run bentoml serve service:ISC_FT_V107 --working-dir inference" 
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://127.0.0.1:3000/healthz || exit 1
      interval: 30s
      timeout: 20s
      retries: 3

  backend:
    container_name: dupish-backend
    build:
      context: .
      dockerfile: dockers/Dockerfile.backend
      args:
        version: '0.0.1'
    ports:
        - "81:81"
    command: "poetry run uvicorn backend.main:app --port 81 --host 0.0.0.0"
    depends_on:
      - dupish
    networks:
      - dupish-network



networks:
  dupish-network:
    driver: bridge



volumes:
  dupish-bento:
    driver: local
