ARG PYTHON_VERSION=3.10-slim
FROM python:${PYTHON_VERSION}

RUN apt update
RUN apt install -y curl python3-pip git

WORKDIR /usr/src

COPY backend/pyproject.toml /usr/src
COPY poetry.lock /usr/src

RUN pip3 install poetry==1.4.2 \
    && poetry export --output requirements.txt --without-hashes

RUN pip3 install -r requirements.txt

COPY backend/ /usr/src
COPY .env /usr/src
CMD ["tail", "-f", "dev/null"]
